2023-10-30 00:00:22,107 [6] ERROR SELMs.Api.Controllers.ApiEquipmentController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'System.Data.Entity.DbSet<SELMs.Models.Category>.Remove(SELMs.Models.Category)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , DbSet`1 , Object )
   at SELMs.Repositories.Implements.EquipmentRepository.DeleteEquipment(Int32 id) in E:\FU\Semester 9\SEP490\repo\SELMs\SELMs\SELMs\Repositories\Implements\EquipmentRepository.cs:line 19
   at SELMs.Api.Controllers.ApiEquipmentController.<DeleteEquipments>d__10.MoveNext() in E:\FU\Semester 9\SEP490\repo\SELMs\SELMs\SELMs\Api\Controllers\ApiEquipmentController.cs:line 163
2023-10-30 13:47:25,723 [9] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:b6fab64e-7eeb-4802-89da-1ffb0fb0b5dd
Error Number:2812,State:62,Class:16
2023-10-30 13:47:26,171 [7] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:b6fab64e-7eeb-4802-89da-1ffb0fb0b5dd
Error Number:2812,State:62,Class:16
2023-10-30 13:48:23,606 [6] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:d1f7fdc5-6a46-405f-a128-226f36bddf2a
Error Number:2812,State:62,Class:16
2023-10-30 13:48:24,045 [9] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:d1f7fdc5-6a46-405f-a128-226f36bddf2a
Error Number:2812,State:62,Class:16
2023-10-30 14:00:32,867 [7] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:ec3a2db2-897f-4385-92b6-62bcc444a39b
Error Number:2812,State:62,Class:16
2023-10-30 14:00:33,353 [6] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:ec3a2db2-897f-4385-92b6-62bcc444a39b
Error Number:2812,State:62,Class:16
2023-10-30 14:40:59,635 [6] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:980bdbb3-9e50-4667-83ec-98c9c8196223
Error Number:2812,State:62,Class:16
2023-10-30 14:40:59,932 [7] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:980bdbb3-9e50-4667-83ec-98c9c8196223
Error Number:2812,State:62,Class:16
2023-11-03 12:08:55,247 [5] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:62421efe-89e2-4c92-92f5-bd8d77f0a44b
Error Number:2812,State:62,Class:16
2023-11-03 12:08:55,492 [7] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:62421efe-89e2-4c92-92f5-bd8d77f0a44b
Error Number:2812,State:62,Class:16
2023-11-03 12:20:40,618 [58] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:5f4ae6e7-4af1-4ff7-a6a3-8f8323301fcc
Error Number:2812,State:62,Class:16
2023-11-03 12:20:40,863 [59] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:5f4ae6e7-4af1-4ff7-a6a3-8f8323301fcc
Error Number:2812,State:62,Class:16
2023-11-03 13:05:47,307 [10] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:76501bb6-5ed8-44f8-b347-1bb4fbc5fa86
Error Number:2812,State:62,Class:16
2023-11-03 13:05:47,533 [9] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:76501bb6-5ed8-44f8-b347-1bb4fbc5fa86
Error Number:2812,State:62,Class:16
2023-11-03 13:13:28,711 [9] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetRolesList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetRoleList>d__6.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 66
ClientConnectionId:50bd8f72-1587-4c71-9d9a-7e9dc41b93d8
Error Number:2812,State:62,Class:16
2023-11-03 13:13:28,958 [6] ERROR SELMs.Api.HumanResource.ApiMemberController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetMembersList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.HumanResource.ApiMemberController.<GetMemberList>d__5.MoveNext() in D:\FULearning\Fall2023\SELMs\SELMs\SELMs\Api\Controllers\ApiMemberController.cs:line 45
ClientConnectionId:50bd8f72-1587-4c71-9d9a-7e9dc41b93d8
Error Number:2812,State:62,Class:16
2023-11-09 22:12:19,037 [47] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 45
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 58
2023-11-09 22:12:51,671 [38] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 45
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 58
2023-11-10 12:46:44,246 [11] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 45
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 58
2023-11-10 12:57:23,061 [30] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 45
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 58
2023-11-10 19:33:12,251 [53] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Api.Controllers.ApiLocationController.<SaveEquipLocationHistory>d__12.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 199
2023-11-12 11:33:23,809 [12] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-12 13:55:50,601 [49] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-12 13:57:16,296 [49] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-12 13:59:34,002 [30] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-12 13:59:44,796 [27] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-12 13:59:46,745 [20] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-13 23:06:24,328 [6] ERROR SELMs.Api.Controllers.ApiEquipmentAllocationController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Object -> List`1
System.Object -> System.Collections.Generic.List`1[[SELMs.Models.Equipment_Allocation_Application_Detail, SELMs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
EquipmentAllocationApplicationDetailDTO -> Equipment_Allocation_Application_Detail
SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO -> SELMs.Models.Equipment_Allocation_Application_Detail

Type Map configuration:
EquipmentAllocationApplicationDetailDTO -> Equipment_Allocation_Application_Detail
SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO -> SELMs.Models.Equipment_Allocation_Application_Detail

Destination Member:
standar_equipment_code
 ---> System.MissingMethodException: Attempted to access a missing method.
   at SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO.get_standar_equipment_code()
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiEquipmentAllocationController.<SaveApplication>d__5.MoveNext()
2023-11-13 23:07:03,999 [6] ERROR SELMs.Api.Controllers.ApiEquipmentAllocationController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Object -> List`1
System.Object -> System.Collections.Generic.List`1[[SELMs.Models.Equipment_Allocation_Application_Detail, SELMs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
EquipmentAllocationApplicationDetailDTO -> Equipment_Allocation_Application_Detail
SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO -> SELMs.Models.Equipment_Allocation_Application_Detail

Type Map configuration:
EquipmentAllocationApplicationDetailDTO -> Equipment_Allocation_Application_Detail
SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO -> SELMs.Models.Equipment_Allocation_Application_Detail

Destination Member:
standar_equipment_code
 ---> System.MissingMethodException: Attempted to access a missing method.
   at SELMs.Api.DTOs.EquipmentAllocationApplicationDetailDTO.get_standar_equipment_code()
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , List`1 , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiEquipmentAllocationController.<SaveApplication>d__5.MoveNext()
2023-11-16 17:52:18,412 [9] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-16 17:53:00,933 [10] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-16 18:02:16,275 [11] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-16 18:02:59,162 [25] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 22:52:24,029 [15] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 22:52:35,346 [12] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 22:55:52,557 [24] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 22:56:02,413 [14] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 22:58:54,223 [25] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:00:14,053 [15] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:01:37,008 [28] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:02:44,929 [40] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:02:52,058 [31] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:03:12,283 [31] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:03:25,416 [28] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-22 23:54:22,958 [65] ERROR SELMs.Api.Controllers.ApiEquipmentController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'System.Collections.Generic.List<object>' to 'System.Threading.Tasks.Task<object>'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Repositories.Implements.EquipmentRepository.GetStandardEquipmentList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\EquipmentRepository.cs:line 126
   at SELMs.Api.Controllers.ApiEquipmentController.<GetStandardEquipmentList>d__5.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiEquipmentController.cs:line 57
2023-11-25 22:02:52,218 [56] ERROR SELMs.Api.Controllers.ApiCategoryController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<SELMs.Models.Equipment>>' to 'System.Collections.Generic.List<SELMs.Models.Equipment>'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.Controllers.ApiCategoryController.<GetCategory>d__6.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiCategoryController.cs:line 78
2023-11-25 22:03:01,426 [67] ERROR SELMs.Api.Controllers.ApiCategoryController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<SELMs.Models.Equipment>>' to 'System.Collections.Generic.List<SELMs.Models.Equipment>'
   at CallSite.Target(Closure , CallSite , Object )
   at SELMs.Api.Controllers.ApiCategoryController.<GetCategory>d__6.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiCategoryController.cs:line 78
2023-11-25 22:05:44,993 [65] ERROR SELMs.Api.Controllers.ApiCategoryController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SELMs.Models.Category' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.Controllers.ApiCategoryController.<GetCategory>d__6.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiCategoryController.cs:line 77
2023-11-25 22:05:50,892 [51] ERROR SELMs.Api.Controllers.ApiCategoryController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SELMs.Models.Category' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at SELMs.Api.Controllers.ApiCategoryController.<GetCategory>d__6.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiCategoryController.cs:line 77
2023-11-25 22:24:29,898 [10] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-25 22:25:20,943 [6] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-30 01:11:16,723 [18] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-11-30 01:12:34,588 [7] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-12-03 23:31:00,729 [14] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-12-03 23:33:30,403 [11] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-12-06 21:00:06,085 [6] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Type Map configuration:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Destination Member:
end_date
 ---> System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at lambda_method(Closure , Object , Project , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Project , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiProjectController.<SaveProject>d__7.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiProjectController.cs:line 101
2023-12-06 21:00:12,671 [8] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Type Map configuration:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Destination Member:
end_date
 ---> System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at lambda_method(Closure , Object , Project , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Project , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiProjectController.<SaveProject>d__7.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiProjectController.cs:line 101
2023-12-06 21:19:45,372 [6] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Type Map configuration:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Destination Member:
create_date
 ---> System.MissingMethodException: Attempted to access a missing method.
   at SELMs.Api.DTOs.ProjectDTO.get_create_date()
   at lambda_method(Closure , Object , Project , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Project , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiProjectController.<SaveProject>d__7.MoveNext()
2023-12-06 21:20:51,679 [6] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Type Map configuration:
ProjectDTO -> Project
SELMs.Api.DTOs.ProjectDTO -> SELMs.Models.Project

Destination Member:
create_date
 ---> System.MissingMethodException: Attempted to access a missing method.
   at SELMs.Api.DTOs.ProjectDTO.get_create_date()
   at lambda_method(Closure , Object , Project , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Project , ResolutionContext )
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at SELMs.Api.Controllers.ApiProjectController.<SaveProject>d__7.MoveNext()
2023-12-06 22:08:38,657 [13] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Proc_GetAllProjectList' expects parameter '@manager_name', which was not supplied.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.Controllers.ApiProjectController.<SearchProjects>d__5.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiProjectController.cs:line 60
ClientConnectionId:43a51b28-997f-414e-8ccc-6b38a87aca58
Error Number:201,State:4,Class:16
2023-12-06 22:09:11,483 [15] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Proc_GetAllProjectList' expects parameter '@manager_name', which was not supplied.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at SELMs.Api.Controllers.ApiProjectController.<SearchProjects>d__5.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiProjectController.cs:line 60
ClientConnectionId:43a51b28-997f-414e-8ccc-6b38a87aca58
Error Number:201,State:4,Class:16
2023-12-06 22:22:04,990 [18] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-12-06 23:36:56,358 [88] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
2023-12-10 01:50:56,921 [6] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.MissingMethodException: Attempted to access a missing method.
   at SELMs.Api.DTOs.InventoryRequestRequest.get_application_details()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<SaveApplication>d__6.MoveNext()
2023-12-10 17:05:09,141 [38] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.GetApplicationDetail(Int32 id) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 97
   at SELMs.Services.Implements.InventoryRequestService.PerformInventoryRequest(PerformInventoryDTO perform) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 17:08:43,702 [13] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SELMs.Models.Inventory_Request_Application_Detail' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 17:10:29,449 [6] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.GetApplicationDetail(Int32 id) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 97
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 17:11:51,079 [8] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.GetApplicationDetail(Int32 id) in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 97
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 17:18:28,840 [6] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'System.Threading.Tasks.Task<SELMs.Models.Inventory_Request_Application_Detail>' to 'SELMs.Models.Inventory_Request_Application_Detail'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext()
2023-12-10 17:21:35,138 [8] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'System.Threading.Tasks.Task<SELMs.Models.Inventory_Request_Application_Detail>' to 'SELMs.Models.Inventory_Request_Application_Detail'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 17:24:36,782 [8] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.<GetApplicationDetail>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 22:35:00,938 [11] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.<GetApplicationDetail>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 22:37:12,891 [6] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.<GetApplicationDetail>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 22:39:57,360 [9] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.<GetApplicationDetail>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-10 22:41:48,017 [9] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SELMs.Repositories.Implements.InventoryRequestApplicationRepository.<GetApplicationDetail>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Repositories\Implements\InventoryRequestApplicationRepository.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Services.Implements.InventoryRequestService.<PerformInventoryRequest>d__9.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<PerformInventoryRequest>d__10.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 167
2023-12-11 00:10:14,800 [11] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SELMs.Models.Equipment' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Services.Implements.InventoryRequestService.<UpdateEquipmentResult>d__11.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<UpdateEquipmentResult>d__11.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 186
2023-12-11 00:10:21,893 [13] ERROR SELMs.Api.Controllers.ApiInventoryRequestController [(null)] - Error: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'SELMs.Models.Equipment' does not contain a definition for 'GetAwaiter'
   at CallSite.Target(Closure , CallSite , Object )
   at SELMs.Services.Implements.InventoryRequestService.<UpdateEquipmentResult>d__11.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Services\Implements\InventoryRequestService.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SELMs.Api.Controllers.ApiInventoryRequestController.<UpdateEquipmentResult>d__11.MoveNext() in C:\Users\84969\Desktop\DoAn\Code\SELMs\SELMs\Api\Controllers\ApiInventoryRequestController.cs:line 186
2023-12-11 09:32:59,103 [21] ERROR SELMs.Api.Controllers.ApiProjectController [(null)] - Error: 
System.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'Proc_GetAllProjectList'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SELMs.Api.Controllers.ApiProjectController.<SearchProjects>d__5.MoveNext() in F:\LyMT\SELMs\SELMs\Api\Controllers\ApiProjectController.cs:line 57
ClientConnectionId:f62601e7-2f9b-4273-9c6b-c6d53407705d
Error Number:2812,State:62,Class:16
2023-12-11 10:04:16,590 [32] ERROR SELMs.Api.Controllers.ApiLocationController [(null)] - Error: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at SELMs.Repositories.Implements.LocationRepository.GetLocationList(Argument arg) in F:\LyMT\SELMs\SELMs\Repositories\Implements\LocationRepository.cs:line 52
   at SELMs.Api.Controllers.ApiLocationController.GetLocationList(Argument args) in F:\LyMT\SELMs\SELMs\Api\Controllers\ApiLocationController.cs:line 59
